/**
 * Concatenates the migrations into a single file, so setting up the database is
 * one copy-paste into the Supabase SQL editor rather than one per migration.
 *
 *   npm run build:sql
 *
 * The output is committed, because the people who most need it are the ones who
 * are not going to run a script to produce it. A test asserts the committed file
 * matches the migrations, so it cannot quietly go stale.
 */

import fs from 'node:fs';
import path from 'node:path';

const MIGRATIONS = path.join(process.cwd(), 'supabase/migrations');
const OUTPUT = path.join(process.cwd(), 'supabase/SETUP.sql');

export function buildCombinedSql(): string {
  const files = fs
    .readdirSync(MIGRATIONS)
    .filter((f) => f.endsWith('.sql'))
    .sort();

  const header = `-- =============================================================================
-- Lawgistics Academy -- complete database setup
-- =============================================================================
-- Paste this whole file into the Supabase SQL editor and run it, once, on a new
-- project. It creates every table, view, policy and trigger the app needs.
--
-- This file is generated by concatenating supabase/migrations/ in order. Do not
-- edit it by hand -- edit the migration and run \`npm run build:sql\`.
--
-- Contains, in order:
${files.map((f) => `--   ${f}`).join('\n')}
-- =============================================================================

`;

  const body = files
    .map((file) => {
      const sql = fs.readFileSync(path.join(MIGRATIONS, file), 'utf8').trimEnd();
      return `\n-- >>> ${file} ${'-'.repeat(Math.max(0, 60 - file.length))}\n\n${sql}\n`;
    })
    .join('\n');

  return `${header}${body}\n`;
}

if (process.argv[1] && process.argv[1].endsWith('build-combined-sql.ts')) {
  fs.writeFileSync(OUTPUT, buildCombinedSql());
  console.log(`Wrote ${OUTPUT}`);
}
