/* Downloads the brand typefaces into assets/ and writes snippets/ss-fonts.liquid.

   Why self hosted rather than a <link> to Google: the brief asks for fast
   loading, and a third party stylesheet costs a DNS lookup, a TLS handshake
   and a round trip before the first character can be painted. The woff2 files
   sit in the theme's own assets, so they come off the same CDN as everything
   else. It also keeps a request to Google off every page view, which matters
   for an Australian shop and its privacy policy.

   Latin only, which is a decision rather than an oversight. Every character
   set in these faces is copy we wrote: headlines, labels, product names. The
   one place a customer's own text could appear is a review, and Judge.me
   renders those in its own widget. latin-ext would more than double the
   download for accented characters this shop will never set. If that ever
   changes, add 'latin-ext' to SUBSETS and re run.

   To change the type: edit STACK, run `npm run fonts`, then update the three
   font stacks in assets/sleep-shop.css to match. The test suite fails if the
   two ever disagree.

   Usage: npm run fonts */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/* The weights here are the ones assets/sleep-shop.css actually asks for.
   Shipping a weight nothing uses is a download nobody needed. */
const STACK = {
  display: { family: 'Playfair Display', faces: [{ weight: 400 }] },
  script: { family: 'Cormorant Garamond', faces: [{ weight: 300, italic: true }] },
  util: { family: 'Inter', faces: [{ weight: 300 }, { weight: 400 }, { weight: 500 }] }
};

const SUBSETS = ['latin'];

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* Ask Google for one face at a time. Asking for the whole set at once returns
   one stylesheet we would then have to unpick, and a single malformed axis
   silently drops a family, which is how the fonts went missing in the first
   place. */
function cssUrl(family, { weight, italic }) {
  const name = family.replace(/ /g, '+');
  const spec = italic ? `ital,wght@1,${weight}` : `wght@${weight}`;
  return `https://fonts.googleapis.com/css2?family=${name}:${spec}&display=swap`;
}

async function fetchFace(family, face) {
  const res = await fetch(cssUrl(family, face), { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${family} ${face.weight}: stylesheet ${res.status}`);
  const css = await res.text();

  /* Google labels each subset with a comment before its @font-face. */
  const wanted = new RegExp(`^\\s*(${SUBSETS.join('|')})\\s*\\*/`);
  const blocks = css.split('/*').filter((b) => wanted.test(b));
  if (!blocks.length) throw new Error(`${family} ${face.weight}: no ${SUBSETS.join('/')} subset`);

  const out = [];
  for (const block of blocks) {
    const subset = block.match(wanted)[1];
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    const range = block.match(/unicode-range:\s*([^;]+);/);
    if (!url) throw new Error(`${family} ${face.weight}: no woff2 in ${subset}`);

    const font = await fetch(url[1]);
    if (!font.ok) throw new Error(`${family} ${face.weight} ${subset}: ${font.status}`);
    const bytes = Buffer.from(await font.arrayBuffer());

    const file =
      `ss-${slug(family)}-${face.weight}${face.italic ? 'i' : ''}-${subset}.woff2`;
    await writeFile(path.join(root, 'assets', file), bytes);
    out.push({ family, face, file, subset, range: range && range[1].trim(), bytes: bytes.length });
  }
  return out;
}

function faceRule({ family, face, file, range }) {
  return `  @font-face {
    font-family: "${family}";
    font-style: ${face.italic ? 'italic' : 'normal'};
    font-weight: ${face.weight};
    font-display: swap;
    src: url({{ '${file}' | asset_url }}) format("woff2");${
      range ? `\n    unicode-range: ${range};` : ''
    }
  }`;
}

async function main() {
  await mkdir(path.join(root, 'assets'), { recursive: true });

  const written = [];
  for (const [role, { family, faces }] of Object.entries(STACK)) {
    for (const face of faces) {
      const got = await fetchFace(family, face);
      got.forEach((g) => written.push({ ...g, role }));
    }
  }

  const total = written.reduce((n, w) => n + w.bytes, 0);
  const snippet = `{%- comment -%}
  The brand typefaces, self hosted. Generated by scripts/fetch-fonts.mjs, so
  edit STACK in that script and re run it rather than editing this file.

  Rendered from ss-tokens.liquid, which every Sleep Shop section renders, so a
  section cannot be added that quietly falls back to Times New Roman. The
  repeated declarations cost nothing: the browser downloads each file once,
  and identical blocks compress to almost nothing over the wire.

  ${SUBSETS.join(' and ')} subset only. ${written.length} files, ${(total / 1024).toFixed(0)} KB in total.
{%- endcomment -%}
<style>
${written.map(faceRule).join('\n')}
</style>
`;

  await writeFile(path.join(root, 'snippets', 'ss-fonts.liquid'), snippet);

  console.log(`${written.length} files, ${(total / 1024).toFixed(0)} KB`);
  for (const w of written) {
    console.log(`  ${w.role.padEnd(8)} ${w.file.padEnd(44)} ${(w.bytes / 1024).toFixed(1)} KB`);
  }
  console.log('\nsnippets/ss-fonts.liquid rewritten');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
